In [1]:
import pandas as pd 
import numpy as np 
import torch 
import torch.nn.functional as fn

In [2]:
w_1 = torch.tensor([0.23], requires_grad=True)

In [3]:
b = torch.tensor([0.9], requires_grad=True)

In [4]:
x_1 = torch.tensor([1.2])
y_1 = torch.tensor([1.0])

In [5]:
z = x_1*w_1+b

In [6]:
a = torch.sigmoid(z)

In [7]:
fn.binary_cross_entropy(a,y_1)

tensor(0.2689, grad_fn=<BinaryCrossEntropyBackward0>)

In [8]:
-np.log(a.detach().cpu().numpy())

array([0.26888928], dtype=float32)

In [9]:
fn.binary_cross_entropy(a,y_1)

tensor(0.2689, grad_fn=<BinaryCrossEntropyBackward0>)

In [10]:
l=fn.binary_cross_entropy_with_logits(z, y_1)
l

tensor(0.2689, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [28]:
from torch.autograd import grad

In [30]:
grad(l,w_1,retain_graph=True)

(tensor([-0.2829]),)

In [13]:
grad(l,b, retain_graph=True)

(tensor([-0.2358]),)

In [22]:
l.backward(retain_graph=True)

In [23]:
w_1.grad

tensor([-1.1317])

In [24]:
b.grad

tensor([-0.9431])

In [25]:
b.grad

tensor([-0.9431])

In [26]:
l


tensor(0.2689, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [29]:
grad(l, w_1, retain_graph=True)

(tensor([-0.2829]),)

In [30]:
w_1.__dir__()

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed_

In [ ]:
You move on to the test set and apply scaling on it but it happens that the max value for that same feature in your test set is 70 ( 100 unfortunately for you happens to exist only in the training set ). Your 70 in the test set if you scale using the test set will be a 1. You feed the 1 ( 70 ) to your model who's trained to consider a 1 as a 100 thus the error.