In [1]:
import pandas as pd 
import numpy as np 
import torch 
import torch.nn.functional as fn

In [2]:
w_1 = torch.tensor([0.23], requires_grad=True)

In [3]:
b = torch.tensor([0.9], requires_grad=True)

In [4]:
x_1 = torch.tensor([1.2])
y_1 = torch.tensor([1.0])

In [5]:
z = x_1*w_1+b

In [6]:
a = torch.sigmoid(z)

In [7]:
fn.binary_cross_entropy(a,y_1)

tensor(0.2689, grad_fn=<BinaryCrossEntropyBackward0>)

In [8]:
-np.log(a.detach().cpu().numpy())

array([0.26888928], dtype=float32)

In [9]:
fn.binary_cross_entropy(a,y_1)

tensor(0.2689, grad_fn=<BinaryCrossEntropyBackward0>)

In [10]:
l=fn.binary_cross_entropy_with_logits(z, y_1)
l

tensor(0.2689, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [11]:
from torch.autograd import grad

In [12]:
grad(l,w_1,retain_graph=True)

(tensor([-0.2829]),)

In [13]:
grad(l,b, retain_graph=True)

(tensor([-0.2358]),)

In [14]:
l.backward()

In [15]:
w_1.grad

tensor([-0.2829])

In [16]:
b.grad

tensor([-0.2358])