In [15]:
import torch as tc
import random
import numpy as np

In [3]:
b  = tc.tensor([0.])
x = tc.tensor([1.2,2.3])
w = tc.tensor([0.5, 0.7])

In [6]:
%timeit x.dot(w)+b

4.32 µs ± 96.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
%timeit x@w+b

4.53 µs ± 135 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
x = tc.tensor([random.random() for _ in range(1000)])
w = tc.tensor([random.uniform(-0.5, 0.5) for _ in range(1000)])

In [10]:
%timeit x.dot(w)+b

4.47 µs ± 119 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
%timeit x@w+b

4.62 µs ± 54.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [27]:
X = tc.tensor([[1.1, 2.0], [4.5, 9.0], [1,1]])

In [48]:
w = tc.tensor([-0.5, 0.5])

In [49]:
w.shape

torch.Size([2])

In [30]:
X.matmul(w)

tensor([0.4500, 2.2500, 0.0000])

# <font color='red'> tensor.dot works only for 1d tensors use tensor.matul for higher dimensional tensors
</font> 


# multiplying matrices with matrices

In [38]:
W = tc.tensor([[0.3, 0.4, 0.5], [0.2, 0.5, 0.1]]).T

In [39]:
W

tensor([[0.3000, 0.2000],
        [0.4000, 0.5000],
        [0.5000, 0.1000]])

In [36]:
X

tensor([[1.1000, 2.0000],
        [4.5000, 9.0000],
        [1.0000, 1.0000]])

In [40]:
X.matmul(w.T)

tensor([[0.7300, 1.4400, 0.7500],
        [3.1500, 6.3000, 3.1500],
        [0.5000, 0.9000, 0.6000]])

In [41]:
tc.matmul(X, W.T)

tensor([[0.7300, 1.4400, 0.7500],
        [3.1500, 6.3000, 3.1500],
        [0.5000, 0.9000, 0.6000]])

# broadcasting

In [46]:
X + np.array([1,2])

tensor([[ 2.1000,  4.0000],
        [ 5.5000, 11.0000],
        [ 2.0000,  3.0000]], dtype=torch.float64)

In [45]:
X+np.array([1, 2, 3])

tensor([[ 2.1000,  6.5000,  4.0000],
        [ 3.0000, 11.0000,  4.0000]], dtype=torch.float64)

In [47]:
1.2*2.1-5.1*3.1+4.6*5.5

12.009999999999998