In [4]:
import torch as tc
import numpy as np 

In [11]:
tens = tc.tensor([np.arange(5), np.arange(5,10)])

In [12]:
tens

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
tens.shape

torch.Size([2, 5])

# from_numpy() 
uses the same array from the memory, without creating a copy of it!

In [24]:
tens = tc.from_numpy(np.array([np.arange(5).astype(float), np.arange(5,10).astype(float)]))
tens

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]], dtype=torch.float64)

# to()
changes the dtype

In [26]:
tens = tens.to(tc.float32)

In [27]:
tens

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [29]:
tens.device

device(type='cpu')

# view()
reshapes the tensor

In [33]:
tens.view((5,2))

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [36]:
tens.view((-1,5))

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [37]:
tens.T

tensor([[0., 5.],
        [1., 6.],
        [2., 7.],
        [3., 8.],
        [4., 9.]])

In [40]:
tens.tolist()

[[0.0, 1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0, 9.0]]

In [44]:
tens.cpu().detach().numpy()

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)